### ISSUE TITLE
 Issue in section 1.2 of ALICE_RAA notebook

### ISSUE THREAD

**Issue by krschmit-cern** [dmuhlhei/ALICE_MC_RAA#1]
Hi,
in section "1.2 Bearbeiten der Daten" of the ALICE_RAA notebook in the second block in line 10 (in the else branch) (line 32 in the ALICE_RAA.py) you wrote `dictEventsCent[cent] = 0` , but I think it has to be `= 1` because this is already the first event in this centrality bin. 

Regards
Kristina

**Comment by dmuhlhei** [comment]
Hi Kristina,
thanks a lot for your comment. You are right, it'll be fixed.
Regards
Daniel
